# Generated by Django 4.1 on 2023-03-07 19:30

from django.db import migrations, models
import staff.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesYTutores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(models.Model, staff.models.Persona),
        ),
    ]
